# Generated by Django 2.2.2 on 2019-06-17 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_groups',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='auth.Group'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
