# Generated by Django 2.2.2 on 2019-06-17 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190617_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='projects', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
