# Generated by Django 2.2.2 on 2019-07-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created', 'name')},
        ),
    ]
