# Generated by Django 2.2.2 on 2019-07-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190702_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='assigned_groups', to='auth.Group'),
        ),
    ]
